language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: FNDDHfP51IUqQRPSlrV/qJD6+kOBPwejqMMXGGRk8Swoo47qlmOrsVEj8kmr1zO3pl0q6K8iKMuopPO2lj7KqE08Fj7J6mjeniHUZvHG4oII9XXiKZG3ouPsU5eLJgfNaUqYO2ZYLsRFDEMWHSL/miVVTvbKNJiMSOhnjnwz3fa+pI1Cv8tMALOl2Q/yGlMhopER7lFXq7/36ytZVh3d/jtF8fraQC5LjSonULQ3DanyQH56H3XZ7kTizBQeMNdsZzFviylUxdMs0whfcHvNRfkRDjacTfyrxHoDlVm6YRYXNx5Iq641Wd/73O9M54mMbAYcdkVQu/khIN4u0tJMkz6Zl4RCjDihkKR61ZQHhsO1hkmI/HkhBaCA9hGfLIZEdMEqvOdBpPv4InD5XSDDX5gJ/8j60yrDHwT24c3dATCRIZldYzegWn1lEmDIsfDFiaYa7ET86q8slultyKCQulzchAwtfaJQ4d8XDIvt1UF/8r/+sm1n2Bd9X1zeD9O2oJn6HVNDCM40inbnUxJ5+ZDuFGmde5F4tBmkANXPmkrucJQISMqt5bdESbzBc/s6xOnwt50F65flrqoxjGIidWPzW8Bhvpoe8QeCRuN1HT4kB4/L/cnYx+G3H3Ti4CUQnrTYoHBRkfWKQobQ0+zBCa1jLLfwsA4dJCOqhp4yZKo=
  app: gtfo-fe
  run: rails db:migrate
env:
  secure: nipZbFyvmZl1k3p7iRgLjIqEZbYeBABGxiyJUvBV7ysNZBOTFk2uUZ8QK6U/dJ/WTz4OkeeyjWhc11VOmQkp68HXO5qqLzeNlYMJCWKkUoup7/32G5IJwfdFj5L/EubudO1TnSKt0Ojzmb+BsstnGXB7ztW4oWJdNYKvDTG1HBSpm+2Av1hYwrJsfuVyLPN+BR7oq9UYSDh6q/uySm9lrz9cnyVp3XKS43Pwo1JiSPpGdWs9DwXBwqKtxsdQij6k80sGB/OwO66hNX7hJzIESjgNI+wW3nco29C+452SnD6tCAiqgH9hLaPL9dtU29cVUBg9XYQpnQUCx27UJzPR5N/T2OyTnmGA6UEJavzPqkPKj7CDkMez1gEY1hrn9s0pFbMqcMifns7G9yHpvj3bGjuuO2zXdKlHoKy2zMfW1c0e0aib1HK/z2sNi+bQYQHHX6ftPt52TnOni1sJjzFb/Cbmd3xQX0lHA/NXBAdc0ISwtM6sYzAsnVYw1yxwE7jK2w28x7qzQ+ktTneQLIo/+lqIhnG+8iLA2aZlCkX1TgNfrJr5HArNywW6lgTuhnAAEtGnlhKCVxvMVHbPFdA/lcztJ2LGC9rQs78bGxtz8WOMCu1iuXBlwLeuGaDJ7AEZziSr1a28w4xQfTZoeCGLrTCNIJTmgW81afnPJbl7FDQ=
