language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: FNDDHfP51IUqQRPSlrV/qJD6+kOBPwejqMMXGGRk8Swoo47qlmOrsVEj8kmr1zO3pl0q6K8iKMuopPO2lj7KqE08Fj7J6mjeniHUZvHG4oII9XXiKZG3ouPsU5eLJgfNaUqYO2ZYLsRFDEMWHSL/miVVTvbKNJiMSOhnjnwz3fa+pI1Cv8tMALOl2Q/yGlMhopER7lFXq7/36ytZVh3d/jtF8fraQC5LjSonULQ3DanyQH56H3XZ7kTizBQeMNdsZzFviylUxdMs0whfcHvNRfkRDjacTfyrxHoDlVm6YRYXNx5Iq641Wd/73O9M54mMbAYcdkVQu/khIN4u0tJMkz6Zl4RCjDihkKR61ZQHhsO1hkmI/HkhBaCA9hGfLIZEdMEqvOdBpPv4InD5XSDDX5gJ/8j60yrDHwT24c3dATCRIZldYzegWn1lEmDIsfDFiaYa7ET86q8slultyKCQulzchAwtfaJQ4d8XDIvt1UF/8r/+sm1n2Bd9X1zeD9O2oJn6HVNDCM40inbnUxJ5+ZDuFGmde5F4tBmkANXPmkrucJQISMqt5bdESbzBc/s6xOnwt50F65flrqoxjGIidWPzW8Bhvpoe8QeCRuN1HT4kB4/L/cnYx+G3H3Ti4CUQnrTYoHBRkfWKQobQ0+zBCa1jLLfwsA4dJCOqhp4yZKo=
  app: gtfo-fe
  run: rails db:migrate
